import React, { useState } from "react";
import {
  X,
  AlertCircle,
  Sparkles,
  Loader2,
  Info,
  CheckCircle2,
  Mail,
  ExternalLink,
  Eye,
  EyeOff,
  Send,
} from "lucide-react";
import { StockWithDetails, SystemSettings } from "../types";

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
}

const BaseModal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  children,
}) => {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-white rounded-2xl w-full max-w-lg shadow-2xl animate-in fade-in zoom-in duration-200 overflow-hidden">
        <div className="px-6 py-4 border-b flex items-center justify-between">
          <h3 className="text-xl font-bold text-gray-800">{title}</h3>
          <button
            onClick={onClose}
            className="p-1 hover:bg-gray-100 rounded-lg text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X size={24} />
          </button>
        </div>
        <div className="p-6">{children}</div>
      </div>
    </div>
  );
};

export const LocationModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: any) => void;
}> = ({ isOpen, onClose, onSubmit }) => {
  const [name, setName] = useState("");
  const [desc, setDesc] = useState("");

  return (
    <BaseModal isOpen={isOpen} onClose={onClose} title="Add New Location">
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Location Name
          </label>
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
            placeholder="e.g. Warehouse North"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Description
          </label>
          <textarea
            value={desc}
            onChange={(e) => setDesc(e.target.value)}
            className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none h-24"
            placeholder="Enter short description..."
          />
        </div>
        <button
          onClick={() => {
            onSubmit({ name, description: desc });
            setName("");
            setDesc("");
          }}
          disabled={!name}
          className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-xl transition-colors disabled:opacity-50"
        >
          Create Location
        </button>
      </div>
    </BaseModal>
  );
};

export const ItemModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: any) => void;
}> = ({ isOpen, onClose, onSubmit }) => {
  const [name, setName] = useState("");
  const [desc, setDesc] = useState("");
  const [min, setMin] = useState(10);

  return (
    <BaseModal isOpen={isOpen} onClose={onClose} title="Register New Item">
      <div className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Item Name
            </label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
              placeholder="e.g. Industrial Drill"
            />
          </div>
          <div className="col-span-1">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Item Code
            </label>
            <div className="px-4 py-2 bg-gray-50 border rounded-lg text-gray-500 text-sm flex items-center space-x-2">
              <Info size={14} />
              <span>Auto-generated by system</span>
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Min. Required Qty
            </label>
            <input
              type="number"
              value={min}
              onChange={(e) => setMin(parseInt(e.target.value))}
              className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
            />
          </div>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Description
          </label>
          <textarea
            value={desc}
            onChange={(e) => setDesc(e.target.value)}
            className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none h-20"
            placeholder="Technical specifications..."
          />
        </div>
        <button
          onClick={() => {
            onSubmit({ name, description: desc, minQuantity: min });
            setName("");
            setDesc("");
            setMin(10);
          }}
          disabled={!name}
          className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-xl transition-colors disabled:opacity-50"
        >
          Register Item
        </button>
      </div>
    </BaseModal>
  );
};

export const LowStockAlertModal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  lowItems: StockWithDetails[];
  aiAnalysis: string;
  loading: boolean;
  settings?: SystemSettings;
}> = ({ isOpen, onClose, lowItems, aiAnalysis, loading, settings }) => {
  const [showEmailPreview, setShowEmailPreview] = useState(false);

  const handleManualEmailHandoff = () => {
    const subject = `URGENT: Low Stock Action Required - ${settings?.organizationName}`;
    let body = `Dear Administrator,\n\nThe following items have dropped below their minimum required threshold:\n\n`;

    lowItems.forEach((item) => {
      body += `Location: ${item.locationName}\nItem: ${item.itemName}\nCurrent: ${item.currentQuantity}\nRequired: ${item.minQuantity}\n-------------------\n`;
    });

    body += `\nPlease initiate procurement immediately.\n\nSent via ${settings?.organizationName}`;

    const targetEmail = settings?.alertEmail || settings?.adminEmail;
    const mailtoUrl = `mailto:${targetEmail}?subject=${encodeURIComponent(
      subject
    )}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoUrl;
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-md">
      <div className="bg-white rounded-3xl w-full max-w-3xl shadow-2xl overflow-hidden max-h-[90vh] flex flex-col">
        <div className="p-6 bg-red-600 text-white flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <AlertCircle size={28} />
            <h3 className="text-2xl font-bold">Critical Low Stock Alert</h3>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-red-500 rounded-full transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        <div className="flex-1 overflow-auto p-6 space-y-6">
          {!loading && lowItems.length > 0 && (
            <div className="bg-emerald-50 border border-emerald-200 p-5 rounded-2xl animate-in slide-in-from-top-4 duration-500">
              <div className="flex items-start justify-between">
                <div className="flex items-start space-x-3">
                  <CheckCircle2
                    className="text-emerald-600 shrink-0 mt-1"
                    size={24}
                  />
                  <div className="flex-1">
                    <h5 className="font-bold text-emerald-900 flex items-center space-x-2">
                      <span>Simulation: Automated Dispatch Successful</span>
                      <Mail size={16} />
                    </h5>
                    <p className="text-sm text-emerald-700 mb-4">
                      The report is ready for delivery to:
                      <span className="block font-mono font-bold text-emerald-800 mt-1 bg-white/50 px-2 py-1 rounded inline-block">
                        {settings?.alertEmail || "admin@enterprise.com"}
                      </span>
                    </p>

                    <div className="flex flex-wrap gap-2">
                      <button
                        onClick={handleManualEmailHandoff}
                        className="flex items-center space-x-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-xl font-bold transition-all shadow-md active:scale-95"
                      >
                        <Send size={16} />
                        <span>Send to my Inbox Now</span>
                      </button>
                      <button
                        onClick={() => setShowEmailPreview(!showEmailPreview)}
                        className="flex items-center space-x-2 text-xs font-bold uppercase tracking-wider text-emerald-600 hover:text-emerald-800 transition-colors bg-white px-3 py-2 rounded-lg border border-emerald-200"
                      >
                        {showEmailPreview ? (
                          <EyeOff size={14} />
                        ) : (
                          <Eye size={14} />
                        )}
                        <span>
                          {showEmailPreview ? "Hide" : "View"} Content
                        </span>
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {showEmailPreview && (
                <div className="mt-4 border-2 border-dashed border-emerald-200 bg-white rounded-xl p-4 font-sans text-gray-800 shadow-inner animate-in fade-in zoom-in duration-300">
                  <div className="border-b pb-2 mb-4">
                    <p className="text-xs text-gray-400">
                      From:{" "}
                      <span className="text-gray-600">
                        Inventory Management System &lt;no-reply@system.com&gt;
                      </span>
                    </p>
                    <p className="text-xs text-gray-400">
                      To:{" "}
                      <span className="text-gray-600">
                        {settings?.adminEmail || settings?.alertEmail}
                      </span>
                    </p>
                    <p className="text-sm font-bold mt-1">
                      Subject: URGENT: Low Stock Action Required -{" "}
                      {settings?.organizationName}
                    </p>
                  </div>
                  <div className="text-xs space-y-3">
                    <p>Dear Administrator,</p>
                    <p>
                      The following items have dropped below their minimum
                      required threshold and require immediate replenishment:
                    </p>
                    <table className="w-full border-collapse">
                      <thead>
                        <tr className="bg-gray-100 text-left">
                          <th className="p-1 border text-[10px]">Location</th>
                          <th className="p-1 border text-[10px]">Item</th>
                          <th className="p-1 border text-[10px] text-center">
                            Current
                          </th>
                          <th className="p-1 border text-[10px] text-center">
                            Required
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {lowItems.map((item) => (
                          <tr key={item.itemId}>
                            <td className="p-1 border">{item.locationName}</td>
                            <td className="p-1 border">{item.itemName}</td>
                            <td className="p-1 border text-center font-bold text-red-600">
                              {item.currentQuantity}
                            </td>
                            <td className="p-1 border text-center">
                              {item.minQuantity}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                    <p className="text-gray-500 italic">
                      This is an automated system alert simulation.
                    </p>
                  </div>
                </div>
              )}
            </div>
          )}

          <div className="space-y-3">
            <h4 className="text-sm font-bold text-gray-400 uppercase tracking-widest">
              Identified Shortages
            </h4>
            {lowItems.map((item) => (
              <div
                key={`${item.locationId}-${item.itemId}`}
                className="flex items-center justify-between bg-red-50 p-4 rounded-xl border border-red-100"
              >
                <div>
                  <p className="font-bold text-gray-900">{item.itemName}</p>
                  <p className="text-sm text-red-600 font-medium">
                    Location: {item.locationName}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-xl font-black text-red-600">
                    {item.currentQuantity}
                  </p>
                  <p className="text-xs text-gray-400 uppercase">
                    Min: {item.minQuantity}
                  </p>
                </div>
              </div>
            ))}
            {lowItems.length === 0 && !loading && (
              <div className="text-center py-12 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-200 text-gray-500">
                <CheckCircle2
                  className="mx-auto mb-3 text-emerald-500"
                  size={40}
                />
                <p className="font-bold text-lg text-gray-700">
                  All Stock Levels Optimal
                </p>
                <p className="text-sm">
                  No items currently require replenishment.
                </p>
              </div>
            )}
          </div>

          <div className="bg-slate-900 text-white p-6 rounded-2xl shadow-lg">
            <div className="flex items-center space-x-2 mb-4">
              <Sparkles className="text-amber-400" size={20} />
              <h4 className="text-lg font-bold">AI Logistics Analysis</h4>
            </div>
            {loading ? (
              <div className="flex flex-col items-center justify-center py-8 space-y-4">
                <Loader2 className="animate-spin text-blue-400" size={40} />
                <p className="text-slate-400 animate-pulse font-medium">
                  Running intelligent inventory scan...
                </p>
              </div>
            ) : (
              <div className="text-slate-300 leading-relaxed whitespace-pre-wrap text-sm border-l-2 border-slate-700 pl-4">
                {aiAnalysis || "Ready to analyze current inventory impact."}
              </div>
            )}
          </div>
        </div>

        <div className="p-6 bg-gray-50 border-t flex flex-col sm:flex-row gap-3 items-center">
          <div className="flex-1 text-xs text-gray-400 flex items-center">
            <AlertCircle size={14} className="mr-1" />
            Inventory Protocol: Report Generated
          </div>
          <button
            onClick={onClose}
            className="w-full sm:w-auto px-8 py-3 bg-gray-800 hover:bg-gray-900 text-white font-bold rounded-xl transition-all"
          >
            Acknowledge & Close
          </button>
        </div>
      </div>
    </div>
  );
};
